#ifndef HEADER_H
#define HEADER_H
	#include <stdio.h>
	#include <stdlib.h>
	#include <string.h>
	#include <ctype.h>
	#include <unistd.h>
	#include <sys/types.h>
	#include <sys/wait.h>
	#include <sys/utsname.h>
	#include <dirent.h>
	#include <sys/stat.h>
	#include <time.h>
	#include <grp.h>
	#include <pwd.h>
	#include <signal.h>
	#include <fcntl.h>
	#include <errno.h>
#endif